# Generated by Django 5.0.1 on 2026-01-16 21:21

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_allow_null_all_fields"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="tour",
                        help_text="Type of content: tour, restaurant, real_estate, local_tips, transportation",
                        max_length=50,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        default="general",
                        help_text='Should always be "general" for this model',
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text='Destination or location name (e.g., "Costa Rica", "Manuel Antonio")',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City/region/area",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title or guide name", max_length=500
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="General description/overview of what this page offers",
                        null=True,
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data specific to content type",
                    ),
                ),
                (
                    "featured_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of featured items with basic info: [{name, url, price, rating}]",
                    ),
                ),
                (
                    "tips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='General tips or advice (e.g., ["Book in advance", "Bring sunscreen"])',
                    ),
                ),
                (
                    "best_season",
                    models.CharField(
                        blank=True,
                        help_text='Best time to visit/book (e.g., "December - April")',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "typical_price_range",
                    models.CharField(
                        blank=True,
                        help_text='Typical price range (e.g., "$50-$200")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(help_text="Original source URL", max_length=1000),
                ),
                (
                    "source_website",
                    models.CharField(
                        blank=True,
                        help_text="Source website name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence score of extraction (0.0 - 1.0)",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="llm_based",
                        help_text="Method used for extraction",
                        max_length=50,
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Roles that can access this guide",
                        size=None,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this guide was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this guide was last updated"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Organization that owns this guide",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_guides",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Guide",
                "verbose_name_plural": "Content Guides",
                "db_table": "content_guides",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "content_type"],
                        name="content_gui_tenant__a7e90b_idx",
                    ),
                    models.Index(
                        fields=["destination"], name="content_gui_destina_6109ee_idx"
                    ),
                    models.Index(
                        fields=["source_website"], name="content_gui_source__48e7b4_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="content_gui_created_c9fcd5_idx"
                    ),
                ],
            },
        ),
    ]
