# Generated by Django 5.0.1 on 2026-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_add_content_guide_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed pricing information: adults, children, students, etc. for tours; ranges for restaurants/hotels",
                verbose_name="Price Details",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price in US dollars (lowest price if multiple categories)",
                max_digits=12,
                null=True,
                verbose_name="Price (USD)",
            ),
        ),
    ]
